# this mapRoles we got from "kubectl get configmap aws-auth -n kube-system -o yaml"

apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::319255955334:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-jmaqpr45zen2
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee # we given in role  this name
      userarn: arn:aws:iam::319255955334:user/vignesh
      username: vignesh    

    - groups:
      - roboshop-admin # we given in role  this name
      userarn: arn:aws:iam::319255955334:user/ramesh
      username: ramesh 

    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::160885265516:user/john
      username: john
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::160885265516:user/rahim
      username: rahim   
kind: ConfigMap
metadata:
  creationTimestamp: "2025-12-16T04:53:38Z"
  name: aws-auth
  namespace: kube-system
  uid: a516bfd2-0044-490a-a8a0-be78563e97b8